# Generated by Django 4.1.7 on 2023-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_user_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="nid",
            field=models.IntegerField(
                help_text="Enter Your National ID", max_length=17
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(help_text="+88019", max_length=14),
        ),
    ]
