# Generated by Django 4.1.7 on 2023-03-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_user_address_alter_user_nid_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nid",
            field=models.CharField(help_text="Enter Your National ID", max_length=17),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(help_text="eg: +8801700000000", max_length=14),
        ),
    ]
